version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm install
    pre_build:
        commands: 
            - npm run test
    build:
        commands:
            - npm run build

artifacts:
    files: /